inv-67 카카오맵 컴포넌트 구현
Nexters/invi pull request #22
Opened 2024-08-02 14:50 UTC by xilucks

* 카카오맵 컴포넌트 구현
* 카카오맵 주소 검색 기능 구현

2024-08-03 07:35 UTC, bepyan commented
### 회의로 결정한 사항

```
L elements
  L recursive.tsx
  L text.tsx
  L ...
L placholders
  L placeholder.tsx
  L ...
```

#### 1. `placeholder`는 별도 디랙토리에 위치합니다.

관심사가 `elements`와 다릅니다.
text.tsx를 수정할 때 text-placeholder.tsx를 참고하지 않을 것 같습니다.

#### 2. `elements` 구조는 그대로 둡니다.

앞으로 파일이 많아질시 element를 찾기 어렵다는 문제에 공감을 하지만, 아직 그 문제가 피부에 와닿지 않기에 추후 불편함을 느낄시 옮기도록 합니다.

#### 3. `element`에 3개 파일이 되는 순간엔 디랙토리를 결도로 만듭니다.

2번 문제에 대한 대응책입니다.

2024-08-06 09:10 UTC, bepyan commented on src/app/(playground)/pg/editor/layout.tsx
> +      />
[제안]
layout에 일일이 주입하는 것이 아닌 유틸성 함수를 만들면 좋을 것 같아요
ex: `src/lib/kakaomap/script.tsx`

2024-08-06 09:11 UTC, bepyan commented on src/components/editor/elements/container.tsx
> +                //     longitude: 126.9786567,
[수정]
불필요한 주석은 제거해주세요.

2024-08-06 09:13 UTC, bepyan commented on src/components/editor/elements/kakao-map-element.tsx
> +import { Badge, Trash } from "lucide-react";
[수정]
이전에 있었던 버그인데, `Badge`는 아이콘이 아닌 ui의 컴포넌트로 가져와 주세요.

2024-08-06 09:17 UTC, bepyan commented on src/components/editor/elements/text.tsx
> +  console.log("texst", editor.state.selectedElement);
[수정]
개인 테스트용 로그는 PR 때 지워주세요.

2024-08-06 09:30 UTC, bepyan requested changes
지도도 안보이고 위치도 설정이 안되는 것 같아요.
수정이 필요해 보입니다.

<img width="470" alt="image" src="https://github.com/user-attachments/assets/08793707-dfc9-44ea-8172-3eb9cb663f34">

2024-08-12 11:56 UTC, xilucks commented on src/components/editor/elements/kakao-map-set-location-button.tsx
> +    }).open();
음 사실 버튼은 제거할 것 같습니다. 일전에 논의되던 상단 버튼의 용도였고 지금은 사이드바로 빠져있거든요..
지금 논의가 어떻게 된건지는 모르겠어서 내일 의견 들어보고 합치겠습니다.

2024-08-17 12:29 UTC, merged